## This prj config file enables only what is neccesaily for the blinky programm to run
## This file was used to get a handle on the flash and ram measurement of Zephyre and enviroment
## ---------------------------------------------------------------------------------------------------


## Configure memory 
CONFIG_MAIN_STACK_SIZE=2048

## Configure GPIO
CONFIG_GPIO=y

## Activate serial console 
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

## Boot-Optimierung 
CONFIG_PRINTK=y
