## Configure memory
CONFIG_MAIN_STACK_SIZE=131072
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_GLIBCXX_LIBCPP=y


#CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y
#CONFIG_THREAD_ANALYZER=y
#CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_NEWLIB_LIBC=y
#CONFIG_HEAP_MEM_POOL_SIZE=16384

## configure RSA Math functions
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_CTR_DRBG_C=y
CONFIG_MBEDTLS_ENTROPY_C=y
#CONFIG_MBEDTLS_RSA_C=y
#CONFIG_MBEDTLS_SHA256=y
#CONFIG_MBEDTLS_PKCS1_V21=y   # PSS + OAEP
CONFIG_MBEDTLS_CIPHER_AES_ENABLED=y
#CONFIG_MBEDTLS_BIGNUM=y

## configure Functions for ECDSA algo
CONFIG_MBEDTLS_ECP_C=y
CONFIG_MBEDTLS_ECDSA_C=y
CONFIG_MBEDTLS_ECDH_C=y
CONFIG_MBEDTLS_SHA256=y
CONFIG_MBEDTLS_ASN1_PARSE_C=y
#CONFIG_MBEDTLS_ASN1_WRITE_C=y
CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED=y

#CONFIG_MBEDTLS_GENPRIME_ENABLED=y
#CONFIG_ENTROPY=y
#CONFIG_ENTROPY_STM32=y
CONFIG_ENTROPY_GENERATOR=y


## Configure Power Management
#CONFIG_PM=y

## Configure USB peripheral

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USB_CDC_ACM=n
CONFIG_USB_DEVICE_STACK=n

# Enable USB device support
#CONFIG_USBD=y

# Enable CDC ACM class (NEW API)
#CONFIG_USBD_CDC_ACM=y

# Initialize automatically
#CONFIG_USBD_CDC_ACM_INIT_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y

# Optional descriptors
#CONFIG_USBD_MANUFACTURER="USB_Debugger_PQC_Implementation"
#CONFIG_USBD_PRODUCT="Zephyr USB"
## Configure GPIO
CONFIG_GPIO=y

## Configure SPI
CONFIG_SPI=n
CONFIG_SPI_STM32=n
CONFIG_DMA=n
CONFIG_SPI_STM32_DMA=n

## Configure PWM
CONFIG_PWM=n
CONFIG_PWM_STM32=n
CONFIG_PINCTRL=y

## Activate serial console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
#CONFIG_USB_UART_CONSOLE=n
#CONFIG_STDOUT_CONSOLE=y
#CONFIG_UART_LINE_CTRL=y

## Configure Logging
CONFIG_LOG=y
CONFIG_LOG_PRINTK=n
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_DEFERRED=y

## Enable SEGGER RTT logging
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=n
CONFIG_PRINTK=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_RTT_MODE_BLOCK=y

## Config Events
CONFIG_EVENTS=y

## Configure Display
CONFIG_DISPLAY=n
CONFIG_FLASH=n
CONFIG_SPI=n

## Enable regulator framwork for LCD backlight
CONFIG_REGULATOR=n

## Configure LVGL
CONFIG_LVGL=n
CONFIG_LV_USE_LABEL=n
CONFIG_LV_USE_LOG=n

CONFIG_LV_COLOR_DEPTH_16=n
CONFIG_LV_FONT_MONTSERRAT_18=n
#CONFIG_LV_Z_MEM_POOL_SIZE=n
##16384
## important to swap upper and lower bytes of the pixels
CONFIG_LV_COLOR_16_SWAP=n

CONFIG_LV_USE_BUTTON=n
CONFIG_LV_USE_ARC=n
CONFIG_LV_USE_IMAGE=n

## General for Ethernet
#CONFIG_POSIX_API=n

## Networking Config
#CONFIG_NETWORKING=n
#CONFIG_NET_IPV4=n
#CONFIG_NET_IPV6=n
#CONFIG_NET_SOCKETS=n
